# Generated by Django 5.2.1 on 2025-05-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='True'),
            preserve_default=False,
        ),
    ]
